#!/bin/bash

echo -e "\e[32mRunning:\e[0m salt-key -L"
salt-key -L

echo -e "\e[32mRunning:\e[0m salt-key -A -y"
salt-key -A -y


echo -e "\e[32mRunning:\e[0m salt '*' test.ping"
salt '*' test.ping

echo -e "\e[32mRunning:\e[0m salt '*' cmd.run 'free -m' "
salt '*' cmd.run 'free -m'
