#!/bin/bash


COUNTER=0
spin='-\|/'
echo -e "\e[93mNot ready yet. Status: ${STATUS}\e[32m"
while [ $COUNTER -lt 10 ]
do
    i=$(( COUNTER %4 ))
    printf "\r${spin:$i:1}"
    sleep .25
    COUNTER=$[$COUNTER+1]

done
echo -ne "\b"
echo -e "\e[93mNot ready yet. Status: ${STATUS}\e[0m"
