#!/bin/bash
echo -e "\e[32mRunning:\e[0m ssh-keygen"
ssh-keygen

NAME=`hostname -d | awk -F. '{print $1}'`
echo -e "\e[32mRunning:\e[0m sl sshkey add ${NAME} --file=/root/.ssh/id_rsa.pub"

sl sshkey add ${NAME}  --file=/root/.ssh/id_rsa.pub
echo -e "\e[32mRunning\e[0m sl sshkey list"
sl sshkey list
