#!/bin/bash

DOMAIN=`hostname -d`
IMAGE="e9081797-ae1f-42e1-9e3a-c3fb75b720de"
KEYNAME=`hostname -d | awk -F. '{print $1}'`
echo -e "\e[32mRunning:\e[0m sl vs create --datacenter=hkg02 --hostname=minion01 --domain=\e[36m${DOMAIN}\e[0m --hourly --key=\e[36m${KEYNAME}\e[0m --cpu=1 --memory=1024 --image=${IMAGE}" 

sl vs create --datacenter=hkg02 --hostname=minion01 --domain=${DOMAIN} --hourly --key=${KEYNAME} --cpu=1 --memory=1024 --image=${IMAGE} --really > /var/log/minion01.log

VSID=`cat /var/log/minion01.log | grep "^id " | awk '{print $2}'`

echo -e "\e[32mRunning:\e[0m sl vs detail ${VSID} "
sl vs detail ${VSID}

echo -e "\e[93mWaiting for instance to come online...\e[0m"
sleep 60
LOOP=0
while [ $LOOP -eq 0 ]
do
    STATUS=`sl vs detail ${VSID} | grep active_transaction | awk '{print $2}'`
    if [ "$STATUS" = "NULL" ]
    then 
        echo -e "\e[32mInstance is ready\e[0m"
        LOOP=1
    else
        echo -e "\e[93mNot ready yet. Status: ${STATUS}\e[0m"
        sleep 30
    fi
done


sl vs detail ${VSID} | grep public_ip | awk '{print $2}' > /root/minion01.ip
