#!/bin/bash

DOMAIN=`hostname -d`

if [ -e /root/minion01.ip ]
then
    echo -e "\e[93mReading \e[96m<MINION IP>\e[93m from /root/minion01.ip ...\e[0m"
else
    echo -e "\e[31mFor this script to work put the minion01 ip address in /root/minion01.ip\e[0m"
    exit
fi

MINION=`cat /root/minion01.ip`
MASTER=`ifconfig eth1 | grep "inet addr:" | awk '{print $2}' | awk -F: '{print $2}'`

echo -e "\e[32mRunning: \e[0m sl dns create ${DOMAIN} "
sl dns create ${DOMAIN}
echo -e "\e[32mRunning: \e[0m sl dns add ${DOMAIN} salt-master A ${MASTER}  "
sl dns add ${DOMAIN} salt-master A ${MASTER}
echo -e "\e[32mRunning: \e[0m sl dns add ${DOMAIN} minion01 A ${MINION} "
sl dns add ${DOMAIN} minion01 A ${MINION} 
echo -e "\e[32mRunning: \e[0m sl dns list ${DOMAIN} "
sl dns list ${DOMAIN}


